## Variables
@username = ckehqja
@password = 1234

@content = 미래를 예측하는 가장 좋은 방법은 그것을 창조하는 것이다
@edit_content = %%%%%%%%%%%%%%%%%%



###  로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("Authorization", response.headers.valueOf("Authorization")); %}




### 글 작성
POST http://localhost:8080/posts
Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{content}}"
}



### 글 수정
PUT http://localhost:8080/posts/48
Authorization:{{Authorization}}
Content-Type: application/json

{
  "content": "{{edit_content}}"
}


### 글 삭제
DELETE http://localhost:8080/posts/24
Authorization:{{Authorization}}
Content-Type: application/json



### 글 조회 - 생성시간
GET http://localhost:8080/posts





### 글 조회 - 생성시간
GET http://localhost:8080/posts?page=1




### 글 조회 - 좋아요 순
GET http://localhost:8080/posts/likes



### 글 조회 기간별
GET http://localhost:8080/posts/period?
    startDate=2024-06-08&endDate=2024-06-10



###단권 글 조회
GET http://localhost:8080/posts/40