## Variables
@username = test1234567
@password = test@1234AAAA
@name = test
@email = test@gmail.com
@headline = test???

### 유정 등록
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "name": "{{name}}",
  "email": "{{email}}",
  "headline": "{{headline}}"
}

###  로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("Authorization", response.headers.valueOf("Authorization")); %}

### 유저 조회
GET http://localhost:8080/users
Authorization:{{Authorization}}

### 유저 프로필 수정
GET http://localhost:8080/auth/customer
Authorization:{{Authorization}}

### 전체 접근 API
GET http://localhost:8080/auth/all
Authorization:{{Authorization}}

### 현재 사용자의 인증정보 확인
GET http://localhost:8080/user/me
Authorization:{{Authorization}}
